# Generated by Django 5.2.4 on 2025-07-18 09:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chaptergeneration_chapterresource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpdf',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pdf'),
        ),
    ]
