# Generated by Django 5.2.4 on 2025-07-18 09:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userpdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpdf',
            name='file',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='pdf'),
            preserve_default=False,
        ),
    ]
